### ISSUE TITLE
Skin lags to hell and back on Profile pages.

### ISSUE THREAD

**Issue by kagan07** [purogamer/MetroForSteamUnoRW11#15]
It literally stutters on Profile pages and it kinda refreshes/reloads sections/GIFs constantly without refreshing the page itself.
It tries to reload Profile Backgrounds again again too.

EDIT : https://media.giphy.com/media/8XLlg0CwpRSytj0FP3/giphy.gif

**Comment by arsildo** [comment]
I am fairly sure the skin is not at fault here. I tried some media overloaded profiles in comparison and I do not have any lag at all.
Can you please provide the link to the profile you show in the GIF ?

**Comment by kagan07** [comment]
> It may be because of your pc, I will make a low consumption version that removes the blur effect. Anyway, I tested it on an old PC from the year 2013, it works fine for me

I don't know what it is but something uses a lot more VRAM than normal Steam on Profile pages. I hope you can find or notice something before 1.0 releases.

**Comment by purogamer** [comment]
![fix](https://user-images.githubusercontent.com/87723899/155263589-75e671a7-f776-461c-ae8a-9672b26154d0.png)

I tried red sigma fix, and it works fine, with edge, open and steam on the profile page with gifs and animated background that does not exceed 1.6 gb of consumption, anyway I think it is necessary to make a low pc version

**Comment by purogamer** [comment]
> VERY IMPORTANT, check to have enabled web rendering by gpu
