### ISSUE TITLE
Stolen work

### ISSUE THREAD

**Issue by redsigma** [purogamer/MetroForSteamUnoRW11#2]
This patch you have posted it's not your patch but a mixed content of the [Unofficial Patch](https://github.com/redsigma/UPMetroSkin) and the vanilla version of [Metro For Steam](https://metroforsteam.com/).

Besides the amount of bugs you haven't even fixed, you stole parts of code from the Unofficial Patch. I compared the code from your files and the files from the Unofficial patch github repository most of them are identical. You didn't even fixed the indentations.

If you want to make your own version of the metro skin then you should fork the github repository of Metro for Steam or the github repository of the Unofficial Patch.

By copying the Unofficial Patch code, you have violated the LICENSE which clearly says that you must give credit and also keep a copy of that LICENSE , either in the description of the repository or as a file called LICENSE.md

To everybody that wants to download this. Please use the Unofficial Patch which is the real patch that i made together with a whole community. At the time of writing this post, the patch fixes every bug that vanilla metro has.Also everybody can join our [Discord Channel](https://discord.com/invite/UZvkvkh) where we can offer help and instructions on how to skin Steam, the library, the friends panel and the Web Pages.

Please remove this repository and fork the original repositories

**Comment by Romanio0089** [comment]
Firstly, you do not need to do a fork to make your own version of a free to use and modify repo.
Secondly, you don't need to keep a copy, you just need to link that original LICENSE.
Thirdly, it is his patch. Even though it might be a mix, it is still modified version of **open source** and **free to use** work, and that makes it his pack.

He does not need to delete this repo and fork the original one, but just properly credit the Unofficial Patch creators. Unofficial Patch is the real patch, and what ??

**Comment by redsigma** [comment]
Forking the original one would also include the fixes and it would be more consistent than copying parts of code. Sure he can edit the code afterwards but it would be easier to reuse code that it's already working. As you say , as long as he gives proper credits to the original makers, it is fine.
